# Generated by Django 4.0.3 on 2022-03-05 22:58

from django.db import migrations, models
import medications.utils
import medications.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[medications.validator.validate_name], verbose_name='Name')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('code', models.CharField(max_length=255, validators=[medications.validator.validate_code], verbose_name='Code')),
                ('image', models.ImageField(upload_to=medications.utils.upload_medication_imagen, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'tbl_medication',
            },
        ),
    ]
