# Generated by Django 4.0.3 on 2022-03-05 21:47

from django.db import migrations, models
import drones.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial number')),
                ('model', models.CharField(choices=[('LIGHTWEIGHT', 'HEAVYWEIGHT'), ('MIDDLEWEIGHT', 'MIDDLEWEIGHT'), ('CRUISERWEIGHT', 'CRUISERWEIGHT'), ('HEAVYWEIGHT', 'HEAVYWEIGHT')], max_length=25, verbose_name='Model')),
                ('weight_limit', models.FloatField(validators=[drones.validator.validate_max_weight], verbose_name='Weight limit')),
                ('battery_capacity', models.IntegerField(default=100, verbose_name='Battery capacity')),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], max_length=25, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
                'db_table': 'tbl_drone',
            },
        ),
    ]
