# Generated by Django 4.0.3 on 2022-03-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.CharField(choices=[('Lightweight', 'Heavyweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], max_length=25, verbose_name='Model'),
        ),
    ]
