# Generated by Django 3.2.12 on 2022-03-08 17:35

from django.db import migrations, models
import django.db.models.deletion
import drones.validator


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_medicinesloadedbydrones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.IntegerField(default=100, validators=[drones.validator.validate_battery_capacity], verbose_name='Battery capacity'),
        ),
        migrations.CreateModel(
            name='HistoryBatteryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.IntegerField(default=100, verbose_name='Battery capacity')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drone', verbose_name='drone')),
            ],
            options={
                'verbose_name': 'HistoryBatteryLevel',
                'verbose_name_plural': 'HistoryBatteryLevels',
                'db_table': 'tbl_history_battery_level',
            },
        ),
    ]
